### ISSUE TITLE
getting error msg on decode

### ISSUE THREAD

**Issue by jerch** [skeeto/race64#1]
Tried your decoder with 1GB of `A`, which should translate into ~750MB of zero'ed bytes. Seems the decoder does not get through:
```bash
$> ./race64 -d data | hexdump
race64: <stdin>:1:invalid input

# compared to base64
$> base64 -d data | hexdump
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
2cb41780
```
Anything I missed?

**Comment by skeeto** [comment]
This is expected since, as mentioned in the README, it only decodes "a 
very rigid format" as it's optimized for speed, not flexibility. Each 
base64 input line (except the last) must be 76 data bytes plus exactly one 
LF byte. This is its own output format, and it's the default output format 
for GNU base64.

**Comment by jerch** [comment]
Ah sorry, overlooked this, thx for clarifying.
